language: node_js csharp
node_js:
  - "stable"
solution: ./src/RayTracer.sln
before_install: cd src/RayTracer/Public
install:
  - nuget restore ./src/RayTracer.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - cd src
  - xbuild /p:Configuration=Debug ./RayTracer.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./RayTracer.Tests/bin/Debug/RayTracer.Tests.dll
  
