language: csharp
solution: src/RayTracer.sln
install:
  - nuget # lets get version number
  - nuget restore src/RayTracer.sln -Verbosity detailed
  - nuget update src/RayTracer.sln -Verbosity detailed
