matrix:
  include:
    - language: csharp
    solution: ./src/RayTracer.sln
    install:
      - nuget restore ./src/RayTracer.sln
      - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
    script:
      - xbuild /p:Configuration=Debug ./src/RayTracer.sln
      - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/RayTracer.Tests/bin/Debug/RayTracer.Tests.dll

  
