language: csharp
solution: ./src/RayTracer.sln
install:
  - nuget restore ./src/RayTracer.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - cd src
  - xbuild /p:Configuration=Debug ./RayTracer.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./RayTracer.Tests/bin/Debug/RayTracer.Tests.dll
  
